### ISSUE TITLE
Error on adding new competencies

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1874]
I think this may be the culprit -- switcheroo of (domain,title) to (title,domain)

https://github.com/ilios/frontend/commit/b746e28b79346b1489e430b0af04f49a38994531#diff-ddb61f6d0e67e223917a7c915be035bfL33

**Comment by dartajax** [comment]
Greetings Ilios Project Support,
 
Not sure if you know of this or not, but we discovered that if you enter competencies with text that is too long (maybe about 160 characters per competency) you get the following error:
 
We are running 3.14.0.
 
There are 2 errors
Ember Data Request POST /api/v1/competencies returned a 400 Payload (application/json) [object Object]
Error: Ember Data Request POST /api/v1/competencies returned a 400
Payload (application/json)
[object Object]
    at new Error (native)
    at Error.r (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-0f0d3bcf01bf8fbced648c74af45db75.js:11:7464)
    at Error.i (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-0f0d3bcf01bf8fbced648c74af45db75.js:37:12829)
    at r.handleResponse (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-0f0d3bcf01bf8fbced648c74af45db75.js:37:18627)
    at r.handleResponse (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-0f0d3bcf01bf8fbced648c74af45db75.js:42:19857)
    at r [as handleResponse] (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-0f0d3bcf01bf8fbced648c74af45db75.js:12:25914)
    at r.c.error (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-0f0d3bcf01bf8fbced648c74af45db75.js:37:19196)
    at u (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-0f0d3bcf01bf8fbced648c74af45db75.js:5:19837)
    at Object.fireWith [as rejectWith] (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-0f0d3bcf01bf8fbced648c74af45db75.js:5:20605)
    at n (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-0f0d3bcf01bf8fbced648c74af45db75.js:6:23793)
Ember Data Request POST /api/v1/competencies returned a 400 Payload (application/json) [object Object]
Error: Ember Data Request POST /api/v1/competencies returned a 400
Payload (application/json)
[object Object]
    at new Error (native)
    at Error.r (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-0f0d3bcf01bf8fbced648c74af45db75.js:11:7464)
    at Error.i (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-0f0d3bcf01bf8fbced648c74af45db75.js:37:12829)
    at r.handleResponse (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-0f0d3bcf01bf8fbced648c74af45db75.js:37:18627)
    at r.handleResponse (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-0f0d3bcf01bf8fbced648c74af45db75.js:42:19857)
    at r [as handleResponse] (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-0f0d3bcf01bf8fbced648c74af45db75.js:12:25914)
    at r.c.error (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-0f0d3bcf01bf8fbced648c74af45db75.js:37:19196)
    at u (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-0f0d3bcf01bf8fbced648c74af45db75.js:5:19837)
    at Object.fireWith [as rejectWith] (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-0f0d3bcf01bf8fbced648c74af45db75.js:5:20605)
    at n (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-0f0d3bcf01bf8fbced648c74af45db75.js:6:23793)
