### ISSUE TITLE
vocabulary manager broken when creating first vocab in a school.

### ISSUE THREAD

**Issue by stopfstedt** [ilios/frontend#1886]
borkage happens _after_ the vocab is saved to the server.

must have something to do with the expand/collapse toggle, and the request param that comes with that.

**Comment by stopfstedt** [comment]
```
error.js:28 Error: Assertion Failed: calling set on destroyed object: <ilios@component:school-vocabularies-list::ember1076>.showNewVocabularyForm = [object Boolean]
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:30207:21)
    at assert (http://localhost:4200/assets/vendor.js:21049:13)
    at Object.assert (http://localhost:4200/assets/vendor.js:29971:34)
    at Object.set (http://localhost:4200/assets/vendor.js:34576:22)
    at Class.set (http://localhost:4200/assets/vendor.js:49277:38)
    at http://localhost:4200/assets/ilios.js:11265:17
    at tryCatch (http://localhost:4200/assets/vendor.js:65999:14)
    at invokeCallback (http://localhost:4200/assets/vendor.js:66014:15)
    at publish (http://localhost:4200/assets/vendor.js:65982:9)
```
