### ISSUE TITLE
Cancel And Save Buttons Don't Function -- Edit Description CI

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1987]
This is related to #1986 since once that occurs, the Save and Cancel Buttons no longer function.  Maybe they are related.  Maybe not.  Either way, see below. Also related to #1988, #1989.

Click the Cancel button and the cursor exits the Description field but no cancellation occurs.

![image](https://cloud.githubusercontent.com/assets/7493331/17754120/e78c0774-6487-11e6-8c31-4d4f52659aa6.png)

The Save button fares no better in this state.  The screen stays like this - need to refresh.  And I do too.

**Comment by saschaben** [comment]
error thrown: `report.get is not a function`

```
report.get is not a function

TypeError: report.get is not a function
    at Class.didReceiveAttrs (http://localhost:4200/assets/ilios.js:2085:32)
    at Class.superWrapper [as didReceiveAttrs] (http://localhost:4200/assets/vendor.js:40403:22)
    at Class.trigger (http://localhost:4200/assets/vendor.js:59850:23)
    at Class.superWrapper [as trigger] (http://localhost:4200/assets/vendor.js:40403:22)
    at Renderer.componentUpdateAttrs (http://localhost:4200/assets/vendor.js:30267:15)
    at ComponentNodeManager_rerender_instrument (http://localhost:4200/assets/vendor.js:29686:22)
    at Object.instrument (http://localhost:4200/assets/vendor.js:32076:23)
    at ComponentNodeManager_rerender [as rerender] (http://localhost:4200/assets/vendor.js:29676:55)
    at Object.componentHook [as component] (http://localhost:4200/assets/vendor.js:25906:21)
    at handleRedirect (http://localhost:4200/assets/vendor.js:61546:21)
```
