### ISSUE TITLE
"Back to Program" Link fails when on a specific programYear page

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#2458]
If you are on a page `[ILIOS]/programs/1/programyears/XXX`, clicking on the "Back to Program" link (rather than the "back to Program years" link) will throw an error:

```
You must provide param `program_id` to `generate`.

Error: You must provide param `program_id` to `generate`.
    at d (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-700308bf8f454af5a9eed1cbeda57fdd.js:22:12841)
    at p.generate (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-700308bf8f454af5a9eed1cbeda57fdd.js:22:15682)
    at T.generate (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-700308bf8f454af5a9eed1cbeda57fdd.js:22:17910)
    at A.generate (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-700308bf8f454af5a9eed1cbeda57fdd.js:23:8604)
    at a.generate (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-700308bf8f454af5a9eed1cbeda57fdd.js:13:26266)
    at a.generateURL (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-700308bf8f454af5a9eed1cbeda57fdd.js:13:3610)
    at a.<anonymous> (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-700308bf8f454af5a9eed1cbeda57fdd.js:8:31560)
    at c.p.get (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-700308bf8f454af5a9eed1cbeda57fdd.js:11:10306)
    at Object.r [as get] (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-700308bf8f454af5a9eed1cbeda57fdd.js:12:17420)
    at t.compute (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-700308bf8f454af5a9eed1cbeda57fdd.js:10:26206)
```

**Comment by stopfstedt** [comment]
we (thanks @saschaben!) narrowed it down to the publication check dropdown in the program-year header. removing that component fixed the nagivation issue. digging into this further.

**Comment by stopfstedt** [comment]
my local env gives me a bit more verbose error message

```
Assertion Failed: You attempted to define a `{{link-to "programYear.publicationCheck"}}` but did not pass the parameters required for generating its dynamic segments. You must provide param `program_id` to `generate`.
```
