### ISSUE TITLE
all X for Instructor Y report throws error

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#2506]
attempting to run any report which requires selection of an instructor throws an error on the attempt to search for a name:

```
Cannot read property 'includes' of null

TypeError: Cannot read property 'includes' of null
    at a.<anonymous> (https://d26vzvixg52o0d.cloudfront.net/assets/ilios-b1a704a492f2f86452a77cf468ffd7cd.js:10:18569)
    at c.p.get (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-47a3abc3eb8af5f1d8abe0c7961b893f.js:11:10306)
    at Object.r [as get] (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-47a3abc3eb8af5f1d8abe0c7961b893f.js:12:17420)
    at t.compute (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-47a3abc3eb8af5f1d8abe0c7961b893f.js:10:26754)
    at t.value (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-47a3abc3eb8af5f1d8abe0c7961b893f.js:10:25436)
    at t.e.value (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-47a3abc3eb8af5f1d8abe0c7961b893f.js:20:19540)
    at e.initialize (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-47a3abc3eb8af5f1d8abe0c7961b893f.js:17:22745)
    at e.peek (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-47a3abc3eb8af5f1d8abe0c7961b893f.js:17:22404)
    at t.evaluate (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-47a3abc3eb8af5f1d8abe0c7961b893f.js:19:26485)
    at e.execute (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-47a3abc3eb8af5f1d8abe0c7961b893f.js:21:23895)
```

**Comment by dartajax** [comment]
I noticed that previously saved reports are fine - this is with the creation of a new report.
