### ISSUE TITLE
Calendar ICS feed is broken

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#3100]
ICS feed link on the calendar throws an error:
```
Compile Error: ics-feed is not a helper

Error: Compile Error: ics-feed is not a helper
    at t.compile (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-7209fae8c902c71f1423222c3811bc3e.js:4573:82)
    at t.compile (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-7209fae8c902c71f1423222c3811bc3e.js:4483:234)
    at t.e.compileStatement (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-7209fae8c902c71f1423222c3811bc3e.js:4268:208)
    at t.compile (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-7209fae8c902c71f1423222c3811bc3e.js:4280:6)
    at a.compile (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-7209fae8c902c71f1423222c3811bc3e.js:3928:41)
    at e.invokeBlock (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-7209fae8c902c71f1423222c3811bc3e.js:4654:201)
    at t.evaluate (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-7209fae8c902c71f1423222c3811bc3e.js:4234:153)
    at e.execute (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-7209fae8c902c71f1423222c3811bc3e.js:4653:112)
    at e.resume (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-7209fae8c902c71f1423222c3811bc3e.js:4650:474)
    at t.handleException (https://d26vzvixg52o0d.cloudfront.net/assets/vendor-7209fae8c902c71f1423222c3811bc3e.js:4689:514) 
```
refers to https://github.com/ilios/common/issues/7

**Comment by stopfstedt** [comment]
fixed.
