### ISSUE TITLE
API version check fails

### ISSUE THREAD

**Issue by stopfstedt** [ilios/frontend#3934]
this is rather maddening.

```
not ok 1250 Chrome 67.0 - Integration | Component | api version check: shows warning on mismatch
    ---
        actual: >
            0
        expected: >
            1
        stack: >
                at Object._callee2$ (http://localhost:7357/assets/tests.js:36120:24)
                at tryCatch (http://localhost:7357/assets/vendor.js:6299:40)
                at Generator.invoke [as _invoke] (http://localhost:7357/assets/vendor.js:6573:22)
                at Generator.prototype.(anonymous function) [as next] (http://localhost:7357/assets/vendor.js:6332:21)
                at step (http://localhost:7357/assets/tests.js:36034:32)
                at http://localhost:7357/assets/tests.js:36045:15
        message: >
            assert.equal($(warningOverlay).length, 1) at integration/components/api-version-check-test.js:33:4
        Log: |
    ...
```

**Comment by stopfstedt** [comment]
seems to be only tied to this PR #3921 . i'll be tracking it over there.
