### ISSUE TITLE
[DEPRECATED] computed property 'sortTerm' was not set on object

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#3960]
We have a lot of these in our test runs. Eg:
```
ok 586 Chrome 68.0 - Acceptance: Instructor Group Details: add instructor
    ---
        Log: |
            { type: 'warn',
              text: '\'DEPRECATION: [DEPRECATED] computed property \\\'sortTerm\\\' was not set on object \\\'<(unknown):ember161273>\\\' via \\\'defineProperty\\\' [deprecation id: ember-meta.descriptor-on-object] See https://emberjs.com/deprecations/v3.x#toc_use-defineProperty-to-define-computed-properties for more details.\\n        at logDeprecationStackTrace (http://localhost:7357/assets/vendor.js:31847:21)\\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:32075:9)\\n        at raiseOnDeprecation (http://localhost:7357/assets/vendor.js:31877:14)\\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:32075:9)\\n        at handleDeprecationWorkflow (http://localhost:7357/assets/vendor.js:79684:9)\\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:32075:9)\\n        at deprecationCollector (http://localhost:7357/assets/vendor.js:79709:5)\\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:32075:9)\\n        at invoke (http://localhost:7357/assets/vendor.js:32087:9)\'\n' }
```

And we should probably figure out where they are coming from and clean them up.

**Comment by stopfstedt** [comment]
```
$ grep -r 'sortTerm' app
app/mixins/live-search-item.js:  sortTerm: '',
app/components/detail-mesh.js:    this.set('sortTerms', ['title']);
app/components/detail-mesh.js:  sortTerms: null,
app/components/detail-mesh.js:  sortedTerms: sort('terms', 'sortTerms'),
app/components/mesh-manager.js:    this.set('sortTerms', ['name']);
app/components/mesh-manager.js:  sortTerms: null,
app/components/user-search.js:  sortTerm: computed('content.firstName', 'content.lastName', function(){
app/components/user-search.js:  sortTerm: oneWay('content.title'),
app/components/user-search.js:        sortTerm: oneWay('content.fullName'),
app/components/user-search.js:      const sortTermA = a.get('sortTerm');
app/components/user-search.js:      const sortTermB = b.get('sortTerm');
app/components/user-search.js:      return sortTermA.localeCompare(sortTermB, locale, { numeric: true });
```

**Comment by stopfstedt** [comment]
see https://www.emberjs.com/deprecations/v3.x/#toc_ember-meta-descriptor-on-object

**Comment by stopfstedt** [comment]
it's the `user-search` component. working on it.
