### ISSUE TITLE
consistent error message when attempting to SAVE new sequence block for a new CI report

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#4085]
Hide Details
2018-09-28T09:37:09-07:00
There is an error
Ember Data Request POST /api/v1/curriculuminventorysequenceblocks returned a 500 Payload (Empty Content-Type) [object Object]
Status Code: 500 Message: The backend responded with an error
Error: Ember Data Request POST /api/v1/curriculuminventorysequenceblocks returned a 500
Payload (Empty Content-Type)
[object Object]
    at n (https://ilios-stage.ucsf.edu/assets/vendor-872b1c82a651088bf001fe01698385ae.js:999:13)
    at n.I (https://ilios-stage.ucsf.edu/assets/vendor-872b1c82a651088bf001fe01698385ae.js:8999:36)
    at new n (https://ilios-stage.ucsf.edu/assets/vendor-872b1c82a651088bf001fe01698385ae.js:9000:54)
    at n.handleResponse (https://ilios-stage.ucsf.edu/assets/vendor-872b1c82a651088bf001fe01698385ae.js:9539:26)
    at n.handleResponse (https://ilios-stage.ucsf.edu/assets/vendor-872b1c82a651088bf001fe01698385ae.js:11298:169)
    at n [as handleResponse] (https://ilios-stage.ucsf.edu/assets/vendor-872b1c82a651088bf001fe01698385ae.js:3278:9)
    at https://ilios-stage.ucsf.edu/assets/vendor-872b1c82a651088bf001fe01698385ae.js:9550:14
    at https://ilios-stage.ucsf.edu/assets/vendor-872b1c82a651088bf001fe01698385ae.js:9550:90
    at n.t.default.extend.ajax.c.error (https://ilios-stage.ucsf.edu/assets/vendor-872b1c82a651088bf001fe01698385ae.js:9550:100)
    at c (https://ilios-stage.ucsf.edu/assets/vendor-872b1c82a651088bf001fe01698385ae.js:582:118)

**Comment by stopfstedt** [comment]
fixed via ilios/ilios#2257
