### ISSUE TITLE
Population of new Instructor Group throws error

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#4111]
If a member is added to a newly instantiated instructor group without a hard refresh and reselection of that new group, an error is thrown:

```
Hide Details
2018-10-10T09:36:53-07:00
There is an error
Cannot read property 'isNew' of undefined
TypeError: Cannot read property 'isNew' of undefined
    at t.e.flushCanonical (https://ilios3-demo.ucsf.edu/assets/vendor-48de5267d272413a89257f02e9d8061c.js:9241:38)
    at t.flushCanonical (https://ilios3-demo.ucsf.edu/assets/vendor-48de5267d272413a89257f02e9d8061c.js:9286:137)
    at n._flushUpdatedRelationships (https://ilios3-demo.ucsf.edu/assets/vendor-48de5267d272413a89257f02e9d8061c.js:9687:255)
    at e.invoke (https://ilios3-demo.ucsf.edu/assets/vendor-48de5267d272413a89257f02e9d8061c.js:1955:176)
    at e.flush (https://ilios3-demo.ucsf.edu/assets/vendor-48de5267d272413a89257f02e9d8061c.js:1948:173)
    at e.flush (https://ilios3-demo.ucsf.edu/assets/vendor-48de5267d272413a89257f02e9d8061c.js:1959:382)
    at e._end (https://ilios3-demo.ucsf.edu/assets/vendor-48de5267d272413a89257f02e9d8061c.js:2003:9)
    at e.end (https://ilios3-demo.ucsf.edu/assets/vendor-48de5267d272413a89257f02e9d8061c.js:1970:243)
    at e._run (https://ilios3-demo.ucsf.edu/assets/vendor-48de5267d272413a89257f02e9d8061c.js:2004:118)
    at e._join (https://ilios3-demo.ucsf.edu/assets/vendor-48de5267d272413a89257f02e9d8061c.js:2003:293)
```

**Comment by stopfstedt** [comment]
can't reproduce this. @saschaben can you confirm that this is still an issue for you? thanks

**Comment by saschaben** [comment]
no longer getting this error --- I am guessing it cleared itself up with the push of frontend 16.4.0?
