### ISSUE TITLE
Attempt to post new top-level vocabulary term throws 500 error

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#4148]
``` Ember Data Request POST /api/v1/terms returned a 500 Payload (Empty Content-Type) [object Object]
Status Code: 500 Message: The backend responded with an error
Error: Ember Data Request POST /api/v1/terms returned a 500
Payload (Empty Content-Type)
[object Object]
    at n (https://ilios-stage.ucsf.edu/assets/vendor-48de5267d272413a89257f02e9d8061c.js:1012:13)
    at n.I (https://ilios-stage.ucsf.edu/assets/vendor-48de5267d272413a89257f02e9d8061c.js:9211:36)
    at new n (https://ilios-stage.ucsf.edu/assets/vendor-48de5267d272413a89257f02e9d8061c.js:9212:54)
    at n.handleResponse (https://ilios-stage.ucsf.edu/assets/vendor-48de5267d272413a89257f02e9d8061c.js:9792:26)
    at n.handleResponse (https://ilios-stage.ucsf.edu/assets/vendor-48de5267d272413a89257f02e9d8061c.js:11771:169)
    at n [as handleResponse] (https://ilios-stage.ucsf.edu/assets/vendor-48de5267d272413a89257f02e9d8061c.js:3380:9)
    at https://ilios-stage.ucsf.edu/assets/vendor-48de5267d272413a89257f02e9d8061c.js:9803:14
    at https://ilios-stage.ucsf.edu/assets/vendor-48de5267d272413a89257f02e9d8061c.js:9803:90
    at n.l.error (https://ilios-stage.ucsf.edu/assets/vendor-48de5267d272413a89257f02e9d8061c.js:9803:100)
    at l (https://ilios-stage.ucsf.edu/assets/vendor-48de5267d272413a89257f02e9d8061c.js:587:118) ```

**Comment by saschaben** [comment]
possibly related to https://github.com/ilios/frontend/issues/4111

**Comment by stopfstedt** [comment]
possibly related to #4085
